package com.calt.buroxz.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuthorityScopeLinkerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorityScopeLinkerAllPropertiesEquals(AuthorityScopeLinker expected, AuthorityScopeLinker actual) {
        assertAuthorityScopeLinkerAutoGeneratedPropertiesEquals(expected, actual);
        assertAuthorityScopeLinkerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorityScopeLinkerAllUpdatablePropertiesEquals(AuthorityScopeLinker expected, AuthorityScopeLinker actual) {
        assertAuthorityScopeLinkerUpdatableFieldsEquals(expected, actual);
        assertAuthorityScopeLinkerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorityScopeLinkerAutoGeneratedPropertiesEquals(AuthorityScopeLinker expected, AuthorityScopeLinker actual) {
        assertThat(actual)
            .as("Verify AuthorityScopeLinker auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorityScopeLinkerUpdatableFieldsEquals(AuthorityScopeLinker expected, AuthorityScopeLinker actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAuthorityScopeLinkerUpdatableRelationshipsEquals(AuthorityScopeLinker expected, AuthorityScopeLinker actual) {
        assertThat(actual)
            .as("Verify AuthorityScopeLinker relationships")
            .satisfies(a -> assertThat(a.getAuthority()).as("check authority").isEqualTo(expected.getAuthority()))
            .satisfies(a -> assertThat(a.getScope()).as("check scope").isEqualTo(expected.getScope()));
    }
}
